# Generated by Django 2.1.7 on 2019-04-17 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_commentform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentForm',
            new_name='Comment',
        ),
    ]
