# Generated by Django 2.1.7 on 2019-04-17 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birthday',
            new_name='birth_date',
        ),
    ]
